### ISSUE TITLE
Script loading without using async and defer .

### ISSUE THREAD

**Issue by NikhilJHA01** [harishsambasivam/JSconcepts#2]
Hi Harish ,

{
  /* <script src="throttling.js"></script>
<script src="asyncvsdefer.js"></script> */
}
// Fetching and execution is done only after the HTML Parsing is done.

** Proposed changes **
 As per me , script without async and defer blocks the HTML parsing therefore it is advised to use async or defer. 

There's a nice article on it if you want insights : "https://flaviocopes.com/javascript-async-defer/ "

/

**Comment by harishsambasivam** [comment]
Ohk, thanks for letting me know @NikhilJHA01 . I'm checking the article and updating it

**Comment by harishsambasivam** [comment]
I mentioned that only for demonstration purpose (:
